---
- hosts: 127.0.0.1
  strategy: linear
  connection: local
  become: yes
  gather_facts: yes

  vars_files:
    - config.yaml

  roles:
    - name: common
      tags: common

    - name: fonts
      tags: fonts

    - name: zsh
      tags: zsh

    - name: neovim
      tags: neovim
    
    - name: tmux
      tags: tmux

    - name: stow_dotfiles
      tags: stow

    # - name: system_defaults
    #   tags: system_defaults
