---

- name: "install packages"
  community.general.npm:
    name: '{{ item }}'
    global: true
    executable: '{{ ansible_user_dir }}/.asdf/shims/npm'
  with_items: '{{ nodejs.packages }}'
  when: nodejs.packages
