---

osx_global_defaults:
  #########################################
  # General
  #########################################

  - { name: "set sidebar icon size to medium", domain: NSGlobalDomain, key: NSTableViewDefaultSizeMode, type: int, value: 2 }
  - { name: "always show scrollbar", domain: NSGlobalDomain, key: AppleShowScrollBars, type: string, value: Always }
  - { name: "disable the over-the-top focus ring animation", domain: NSGlobalDomain, key: NSUseAnimatedFocusRing, type: bool, value: false }
  - { name: "increase window resize speed for cocoa applications", domain: NSGlobalDomain, key: NSWindowResizeTime, type: float, value: 0.001 }
  - { name: "save to disk (not to icloud) by default", domain: NSGlobalDomain, key: NSDocumentSaveNewDocumentsToCloud, type: bool, value: false }
  - { name: "disable the “are you sure you want to open this application?” dialog", domain: com.apple.LaunchServices, key: LSQuarantine, type: bool, value: false }
  - { name: "disable automatic capitalization as it’s annoying when typing code", domain: NSGlobalDomain, key: NSAutomaticCapitalizationEnabled, type: bool, value: false }
  - { name: "disable smart dashes as they’re annoying when typing code", domain: NSGlobalDomain, key: NSAutomaticDashSubstitutionEnabled, type: bool, value: false }
  - { name: "disable automatic period substitution as it’s annoying when typing code", domain: NSGlobalDomain, key: NSAutomaticPeriodSubstitutionEnabled, type: bool, value: false }
  - { name: "disable smart quotes as they’re annoying when typing code", domain: NSGlobalDomain, key: NSAutomaticQuoteSubstitutionEnabled, type: bool, value: false }
  - { name: "disable auto-correct", domain: NSGlobalDomain, key: NSAutomaticSpellingCorrectionEnabled, type: bool, value: false }

  #########################################
  # Finder
  #########################################

  - { name: "allow quitting via ⌘ + q; doing so will also hide desktop icons", domain: com.apple.finder, key: QuitMenuItem, type: bool, value: true }
  - { name: "disable window animations and get info animations", domain: com.apple.finder, key: DisableAllAnimations, type: bool, value: true }
  - { name: "set desktop as the default location for new finder windows", domain: com.apple.finder, key: NewWindowTarget, type: string, value: "PfDe" }
  - { name: "set target path for new finder windows", domain: com.apple.finder, key: NewWindowTargetPath, type: string, value: "file://{{ lookup('env', 'HOME') }}/Desktop/" }
  - { name: "show icons for hard drives, servers, and removable media on the desktop", domain: com.apple.finder, key: ShowExternalHardDrivesOnDesktop, type: bool, value: true }
  - { name: "show hard drive icons on desktop", domain: com.apple.finder, key: ShowHardDrivesOnDesktop, type: bool, value: true }
  - { name: "show mounted servers on desktop", domain: com.apple.finder, key: ShowMountedServersOnDesktop, type: bool, value: true }
  - { name: "show removable media on desktop", domain: com.apple.finder, key: ShowRemovableMediaOnDesktop, type: bool, value: true }
  - { name: "show hidden files by default", domain: com.apple.finder, key: AppleShowAllFiles, type: bool, value: true }
  - { name: "show all filename extensions", domain: com.apple.finder, key: AppleShowAllExtensions, type: bool, value: true }
  - { name: "show status bar", domain: com.apple.finder, key: ShowStatusBar, type: bool, value: true }
  - { name: "show finder path bar", domain: com.apple.finder, key: ShowPathbar, type: bool, value: true }
  - { name: "display full posix path as finder window title", domain: com.apple.finder, key: _FXShowPosixPathInTitle, type: bool, value: false }
  - { name: "keep folders on top when sorting by name", domain: com.apple.finder, key: _FXSortFoldersFirst, type: bool, value: true }
  - { name: "when performing a search, search the current folder by default", domain: com.apple.finder, key: FXDefaultSearchScope, type: string, value: "SCcf" }
  - { name: "disable the warning when changing a file extension", domain: NSGlobalDomain, key: FXEnableExtensionChangeWarning, type: bool, value: false }
  - { name: "enable spring loading for directories", domain: com.apple.finder, key: com.apple.springing.enabled, type: bool, value: true }
  - { name: "remove the spring loading delay for directories", domain: com.apple.finder, key: com.apple.springing.delay, type: float, value: 0 }
  - { name: "avoid creating .ds_store files on network or usb volumes", domain: com.apple.desktopservices, key: DSDontWriteNetworkStores, type: bool, value: true }
  - { name: "don't write ds_store files on usb drives", domain: com.apple.desktopservices, key: DSDontWriteUSBStores, type: bool, value: true }
  # Four-letter codes for the other view modes: `icnv`, `clmv`, `glyv`
  - { name: "use list view in all finder windows by default", domain: com.apple.finder, key: FXPreferredViewStyle, type: string, value: "Nlsv" }
  - { name: "open disk images as read-only", domain: com.apple.frameworks.diskimages, key: auto-open-ro-root, type: bool, value: true }
  - { name: "automatically open a new finder window when a volume is mounted", domain: com.apple.frameworks.diskimages, key: auto-open-ro-root, type: bool, value: true }
  - { name: "open new windows for new removable disks", domain: com.apple.finder, key: OpenWindowForNewRemovableDisk, type: bool, value: true }
  - { name: "disable the warning before emptying the trash", domain: com.apple.finder, key: WarnOnEmptyTrash, type: bool, value: false }

  #########################################
  # Dock
  #########################################

  - { name: "orient macos dock to the bottom of the screen", domain: com.apple.dock, key: orientation, type: string, value: bottom }
  - { name: "set the icon size of dock items to 42 pixels (monterrey)", domain: com.apple.dock, key: tilesize, type: float, value: 42 }
  - { name: "remove the auto-hiding dock delay", domain: com.apple.dock, key: autohide-delay, type: float, value: 0.0 }
  - { name: "remove the animation when hiding/showing the dock", domain: com.apple.dock, key: autohide-time-modifier, type: float, value: 0.0 }
  - { name: "automatically hide and show the dock", domain: com.apple.dock, key: autohide, type: bool, value: true }
  - { name: "don’t show recent applications in dock", domain: com.apple.dock, key: autohide, type: bool, value: true }
  - { name: "change minimize/maximize window effect to scale", domain: com.apple.dock, key: show-recents, type: bool, value: false }
  - { name: "minimize windows into their application’s icon", domain: com.apple.dock, key: mineffect, type: string, value: scale }
  - { name: "enable spring loading (dragging items to app icons) for all dock items", domain: com.apple.dock, key: enable-spring-load-actions-on-all-items, type: bool, value: true }
  - { name: "show indicator lights for open applications in the dock", domain: com.apple.dock, key: show-process-indicators, type: bool, value: true }
  - { name: "don’t animate opening applications from the dock", domain: com.apple.dock, key: launchanim, type: bool, value: false }
  - { name: "speed up mission control animations", domain: com.apple.dock, key: expose-animation-duration, type: float, value: 0.1 }
  - { name: "disable dashboard", domain: com.apple.dock, key: mcx-disabled, type: bool, value: true }
  - { name: "don’t show dashboard as a space", domain: com.apple.dock, key: dashboard-in-overlay, type: bool, value: true }
  - { name: "don’t automatically rearrange spaces based on most recent use", domain: com.apple.dock, key: mru-spaces, type: bool, value: false }
  - { name: "expand save panel by default", domain: NSGlobalDomain, key: NSNavPanelExpandedStateForSaveMode, type: bool, value: true }
  - { name: "auto-expand navigation panel for save modes", domain: NSGlobalDomain, key: NSNavPanelExpandedStateForSaveMode2, type: bool, value: true }
  - { name: "expand print panel by default", domain: NSGlobalDomain, key: PMPrintingExpandedStateForPrint, type: bool, value: true }
  - { name: "expand information for printing", domain: NSGlobalDomain, key: PMPrintingExpandedStateForPrint2, type: bool, value: true }

  #########################################
  # Activity Monitor
  #########################################

  - { name: "show the main window when launching activity monitor", domain: com.apple.ActivityMonitor, key: OpenMainWindow, type: bool, value: true }
  - { name: "visualize cpu usage in the activity monitor dock icon", domain: com.apple.ActivityMonitor, key: IconType, type: int, value: 5 }
  - { name: "show all processes in activity monitor", domain: com.apple.ActivityMonitor, key: ShowCategory, type: int, value: 0 }
  - { name: "sort activity monitor results by cpu usage", domain: com.apple.ActivityMonitor, key: SortColumn, type: string, value: "CPUUsage" }
  - { name: "set activity monitor sorting direction", domain: com.apple.ActivityMonitor, key: SortDirection, type: int, value: 0 }

  #########################################
  # Screenshots
  #########################################

  - { name: "disable shadow in screenshots", domain: com.apple.screencapture, key: disable-shadow, type: bool, value: true }
  - { name: "remove date and time from the screenshot file names", domain: com.apple.screencapture, key: include-date, type: bool, value: false }
  - { name: "save screenshots to the screenshots folder", domain: com.apple.screencapture, key: location, type: string, value: "~/Pictures/Screenshots" }
  - { name: "display thumbnail after taking a screenshot", domain: com.apple.screencapture, key: show-thumbnail, type: bool, value: true }
  # other options: BMP, GIF, JPG, PDF, TIFF
  - { name: "save screenshots in png format", domain: com.apple.screencapture, key: type, type: string, value: "png" }

  #########################################
  # Keyboard
  #########################################

  - { name: "disable press-and-hold for keys in favor of key repeat", domain: NSGlobalDomain, key: ApplePressAndHoldEnabled, type: bool, value: false }
  - { name: "set a blazingly fast keyboard repeat rate", domain: NSGlobalDomain, key: KeyRepeat, type: int, value: 1 }
  - { name: "set key repeat value", domain: NSGlobalDomain, key: InitialKeyRepeat, type: int, value: 10 }
  # (e.g. enable Tab in modal dialogs)
  - { name: "enable full keyboard access for all controls", domain: NSGlobalDomain, key: AppleKeyboardUIMode, type: int, value: 3 }

  #########################################
  # Miscellaneous
  #########################################

  - { name: "increase sound quality for bluetooth headphones/headsets", domain: com.apple.BluetoothAudioAgent, key: "Apple Bitpool Min (editable)", type: int, value: 40 }
  - { name: "don't use natural scrolling", domain: NSGlobalDomain, key: com.apple.swipescrolldirection, type: bool, value: false }
  - { name: "set dark mode", domain: NSGlobalDomain, key: AppleInterfaceStyle, type: string, value: Dark }
  - { name: "quit printer app once jobs are complete", domain: com.apple.print.PrintingPrefs, key: 'Quit When Finished', type: boolean, value: true }
  - { name: "don't open imagecapture when camera plugged in", domain: com.apple.ImageCapture, key: disableHotPlug, type: boolean, value: true }

osx_alt_tab_defaults:
  - { name: "alt-tab | show windows from screen showing alt-tab", domain: com.lwouis.alt-tab-macos, key: screensToShow, type: string, value: 1, state: present }
  - { name: "alt-tab | show windows active space only", domain: com.lwouis.alt-tab-macos, key: spacesToShow, type: string, value: 1, state: present }
  - { name: "alt-tab | do not send crash reports", domain: com.lwouis.alt-tab-macos, key: crashPolicy, type: string, value: 0, state: present }
  - { name: "alt-tab | disable automatic updates", domain: com.lwouis.alt-tab-macos, key: SUAutomaticallyUpdate, type: bool, value: false, state: present }
  - { name: "alt-tab | disable automatic update checks", domain: com.lwouis.alt-tab-macos, key: SUEnableAutomaticChecks, type: bool, value: false, state: present }
  # use lowercase `\u` to pass unicode
  - { name: "alt-tab | set shortcuts #1", domain: com.lwouis.alt-tab-macos, key: holdShortcut, type: string, value: "\u2318", state: present }

osx_rectangle_defaults:
  - { name: "rectangle | set spectacle-compatible shortcuts", domain: com.knollsoft.Rectangle, key: alternateDefaultShortcuts, type: int, value: 0, state: present }
  - { name: "rectangle | launch on login", domain: com.knollsoft.Rectangle, key: launchOnLogin, type: int, value: 1, state: present }
